theme: jekyll-theme-minimal
title: Sujan Balami
description: # Tutorial 
author: Sujan Balami

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
- README.md
