theme: jekyll-theme-minimal
title: Tutorial
description: Here you will find tutorial of some statistical and phylogenetic analysis 
author: Sujan Balami

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
- README.md
