theme: jekyll-theme-minimal
title: Sujan Balami
description: Hello everyone! welcome to my tutorial page hosted on GitHub. Here, I have complied some basic tutorial of statistical and phylogenetic analysis.
image: "ss.jpg"
author: Sujan Balami

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
- README.md
- CONTRIBUTING.md
- CODE_OF_CONDUCT.md
- LICENSE.md
- ss.jpg
