theme: jekyll-theme-minimal
title: Sujan Balami
subtitle: HEllo Everyone! welcome to my tutorial page hosted on GitHub. Here, I have complied some basic tutorial of statistical and phylogenetic analysis. 
description: Tutorial
author: Sujan Balami

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
- README.md
