theme: jekyll-theme-minimal
title: Tutorial | Home
description: Hello everyone! welcome to my tutorial page hosted on GitHub. Here, I have complied some basic tutorial of statistical and phylogenetic analysis. Statistical analysis can be execute in R statistical programming. Different free softwares can be used for phylogenetic analysis.
twitter_username: BalamiSujan

plugins:
  - jekyll-relative-links
  - jekyll-feed
relative_links:
  enabled: true
  collections: true
include:
- README.md
- CONTRIBUTING.md
- CODE_OF_CONDUCT.md
- LICENSE.md
- ss.jpg
